version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "<APP_NAME>"
          ContainerPort: <SERVICE_PORT>
hooks:
  - AfterAllowTestTraffic: "arn:aws:lambda:<AWS_DEFAULT_REGION>:<AWS_ACCOUNT_ID>:function:validate"

