version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "<APP_NAME>"
          ContainerPort: <SERVICE_PORT>
hooks:
  - AfterAllowTestTraffic: "arn:aws:lambda:us-east-1:154604790077:function:validate"

